# Generated by Django 5.1 on 2024-08-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
