# Generated by Django 5.1 on 2024-09-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_officehours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_image/'),
        ),
    ]
