# Generated by Django 5.1 on 2024-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
