# Generated by Django 5.1 on 2024-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehours',
            name='date',
            field=models.CharField(default='1390-02-05', max_length=60),
            preserve_default=False,
        ),
    ]
