# Generated by Django 5.1 on 2024-09-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_officehours_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
