# Generated by Django 5.1 on 2024-09-10 23:17

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_chatmessage_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', django_jalali.db.models.jDateTimeField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_deadline', to='landing.course')),
            ],
        ),
    ]
