# Generated by Django 5.1 on 2024-09-10 23:50

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_homeworkdeadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehours',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
